name: lms_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.5.1+41

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3
  dio: ^4.0.0-beta7
  permission_handler: ^8.3.0
  flutter_svg: ^0.23.0
  dropdown_below: ^0.0.6
  dropdown_search: ^0.4.9
  toast: ^0.1.5
  http: ^0.13.1
  get: ^4.1.4
  auto_size_text: ^2.1.0
  get_storage: ^2.0.2
  flutter_rating_bar: ^4.0.0
  shared_preferences: ^2.0.5
  flutter_webview_plugin: ^0.4.0
  flutter_portal: ^0.4.0
  reactive_forms: 10.1.0
  extended_nested_scroll_view: ^3.0.0
  font_awesome_flutter: ^9.0.0
  flutter_widget_from_html_core: 0.6.1+1
  loading_skeleton: ^1.0.2
  flutter_cache_manager: ^3.0.2
  file_picker: ^3.0.1
  file_utils: ^1.0.0
  url_launcher: ^6.0.6
  flutter_screenutil: ^5.0.0+2
  http_auth: ^1.0.0
  flutter_switch: ^0.3.2
  slide_countdown: ^0.0.4
  smart_select: ^4.3.2
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^8.1.1+1
  rxdart: ^0.26.0
  edge_alert: ^0.0.1
  flutter_smart_dialog: ^2.3.8
  stripe_sdk:
    git: https://github.com/s2nventures/stripe-sdk
  package_info_plus: ^1.3.0
  percent_indicator: ^3.4.0
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  razorpay_flutter: ^1.2.7
  open_document:
    git: https://github.com/emran92/open_document
  advance_pdf_viewer: ^2.0.0
  webview_flutter: ^3.0.0
  flutter_facebook_auth: ^4.1.1
  google_sign_in: ^5.2.4
  connection_notifier: ^0.0.1
  pod_player: ^0.0.6
  flutter_inappwebview: ^5.4.1+1
  vdocipher_flutter: ^1.0.0-beta.6
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  jitsi_meet:
    git:
      url: https://github.com/dispersik/jitsi_meet_fork
      ref: master
  sn_progress_dialog: ^1.0.8
  carousel_slider: ^4.1.1
  scaled_list: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  import_sorter: ^4.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.jpg"

flutter_native_splash:
  background_image: "images/Splash.png"
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: font/AvenirNextLTPro-Regular.otf